# merges the rds managed-credential secret + app jwt secret into one k8s secret for the phase 7 deployment
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: realworld-app
  namespace: app-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: realworld-app
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # host/port/dbname aren't in the rds managed secret (it's username+password only), and they're not secret anyway
        DB_URL: "jdbc:postgresql://realworld-aws-dev-db.cur8yieugusf.us-east-1.rds.amazonaws.com:5432/realworld"
        DB_USERNAME: "{{ .username }}"
        DB_PASSWORD: "{{ .password }}"
        JWT_SECRET: "{{ .JWT_SECRET }}"
  dataFrom:
    - extract:
        key: "rds!db-e9b9af15-1f1c-47ba-8286-564ee18371dd"
    - extract:
        key: "dev/realworld/app"
